---
name: .NET CI (trx -> junit)

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj

      - name: Build
        run: dotnet build --configuration Debug src/Presentation/Nop.Web/Nop.Web.csproj

      - name: Run tests (produce TRX)
        run: |
          mkdir -p TestResults
          dotnet test src/Tests/Nop.Tests/Nop.Tests.csproj \
            --logger "trx;LogFileName=TestResults/TestResults.trx" \
            --no-build

      - name: Install trx2junit
        run: dotnet tool install --global trx2junit

      - name: Convert TRX to JUnit
        env:
          PATH: ${{ env.PATH }}:${{ github.workspace }}/.dotnet/tools:$HOME/.dotnet/tools
        run: |
          # convert TRX -> JUnit
          trx2junit TestResults/TestResults.trx -o TestResults/TESTS-Nop.Tests.xml

      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: TestResults/TESTS-*.xml

      - name: Publish app
        if: success()
        run: dotnet publish --configuration Release src/Presentation/Nop.Web/Nop.Web.csproj --output published
